#!/bin/bash

if [[ -z $1 ]]; then
    exit 1
fi

for ff in $(cat 1); do
    if [[ $(grep -q $ff 2) ]]; then
        echo "Есть повторяющееся имя $ff"
        exit 1
    fi
done

echo "Повторяющихся имен нет"
