#!/bin/bash

if [[ -z $1 ]]; then
    exit 1
fi

ff=$(cat $1 | awk 'END {print NR}')
sf=$(cat $2 | awk 'END {print NR}')

if [[ $ff == $sf ]]; then
    echo "Во всех группах одинаковое колличество человек"
else
    echo "У вас всё плохо"
    exit 1
fi
